export const ActionType = {
    GET_ARTIST_RESULT: 'GET_ARTIST_RESULT',
    ADD_TO_FAVORITE: 'ADD_TO_FAVORITE',
    REMOVE_FROM_FAVORITE: 'REMOVE_FROM_FAVORITE',
    SET_SELECTED_ARTIST: 'SET_SELECTED_ARTIST'
}

export default ActionType;